# filepath: /Users/lontray/Documents/repos/DutchPal/k8s-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dutchpal-deployment
  namespace: dutchpal  # Use a unique namespace for isolation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dutchpal
  template:
    metadata:
      labels:
        app: dutchpal
    spec:
      containers:
      - name: dutchpal-container
        image: docker.io/zekeriyakoca/dutchpal-fastapi:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 40001
        env:
        - name: ENV
          value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: dutchpal-api
  namespace: dutchpal
spec:
  selector:
    app: dutchpal
  ports:
    - protocol: TCP
      port: 40001
      targetPort: 40001
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dutchpal-api-ingress
  namespace: dutchpal
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: "nginx"
  rules:
    - host: ""
      http:
        paths:
          - path: /dutchpal-api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: dutchpal-api
                port:
                  number: 40001